url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: BrainwaveS
email: #
description: "We are BrainwaveS Neurorehab Solutions, and we are here to help people through their stroke rehab process using cutting edge VR technology."


# Team names, titles and social links
people:
- name: Dr. Bhasi Sukumaran 
  pic: 1
  position: Founder
  about: Holds a PhD in Clinical Psychology (specialty-Neuropsychology) and an MPhil in Clinical Psychology, both from NIMHANS. Has over 25 years of experience. Currently Professor & Head, Dept of Clinical Psychology, at SRM Medical College Hospital and Research Centre Consultant Clinical Neuropsychologist, SIMS Hospitals, Vadapalani, Chennai. Research interests in Neurocognitive remediation involving Brain computer and Virtual Reality. Is an omnivorous reader and an avid nature/wildlife/animal enthusiast who loves trekking and motorcycle touring
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/dr-bhasi-sukumaran-ab33999/

- name: Mr. Sreeram. R 
  pic: 2
  position: Chief Technology Officer
  about:  Holds an M.Tech in Cybersecurity Systems and Networks. Currently Infrastructure Engineer at Ecorp SaS. Is an expert at network security protocols and infrastructure specialist in delivering cost-effective solutions. First startup gig at 22, a decade of experience with early stage startups. Has held cross-functional roles in 3 different startups. ○ Big Data & Cybersecurity (Government of India) ○ Fintech (European) o Privacy-enabled smartphones (European). Is a self professed technophile, footballer, and a foodie
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sreeramr86/

- name: Aniket Sahoo
  pic: 3
  position: Junior Research Associate
  about: Holds a B.tech in Mechatronics from SRM institute of science and technology. Has worked as inturn in “BrainwaveS” since before its incorporation and is now a full-time employee. Has skills in fields like embedded systems, VR, game development, system integration, sensor fusion and web development. Worked on various projects on topics like robotics, automation, waste management and soft actuators. Passionate about solving problems using new technologies. Holds interests in robotics, aquariums and video games.
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/aniket-sahoo-30b66b193/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/brainwaves-neurorehab-solutions/mycompany/

# Postal address (add as many lines as necessary)
address:
  - line: SRMIST, Kattankulathur
  - line: Chennai, Tamil Nadu, 603203

# Build settings
markdown: kramdown
permalink: pretty