version: '2.1'

services:
  webapp:
    image: jekyll/builder:$JEKYLL_VERSION
    container_name: webapp
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./jekyll:/srv/jekyll
    command: jekyll serve
    profiles:
      - local
      - production

  nginx:
    image: nginx:1.20-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/templates:/etc/nginx/templates/
      - ./config/nginx/params:/etc/nginx/params/
      - ./config/nginx/sites-enabled:/etc/nginx/conf.d
      - ./config/letsencrypt/:/certs/
      - ./volumes/nginx/logs:/var/log/nginx
    depends_on:
      - webapp
    profiles:
      - production

